// All user-facing UI strings live here (JP/EN mix) for later i18n.
export const strings = {
  appTitle: 'なんでだっけ？',
  nande: 'なんで？',
  respond: '答える',
  checkUnderstanding: '❓ 答えて理解を確認 / Check my understanding',
  gotIt: '分かった',
  understoodTitle: 'このノードを理解済みにする / Mark understood',
  understoodProgress: '理解',
  defaultQuestion: 'why is this the case?',
  answerPlaceholder: 'あなたの答えを入力… / Type your answer… (Enter で送信)',
  yourAnswerLabel: 'あなたの答え',
  ideaLabel: '💡 あなたの問い',
  ideaPlaceholder: '「もし〜だったら？」など、自分の問いを入力… / Your own question or idea…',
  newIdea: '💡 自分の問い / Ask your own',
  nextChunkMenu: '→ 次のチャンク / Next chunk',
  regenerate: '↻ 再生成 / Regenerate',
  deleteNode: '🗑 削除 / Delete',
  deleteConfirmOne: 'このノードを削除しますか？ / Delete this node?',
  deleteConfirmMany: (n: number) =>
    `このノードと${n - 1}個の子ノードを削除しますか？ / Delete this node and ${n - 1} descendant(s)?`,
  backToSource: '↩ 元のテキストへ',
  askPlaceholder: '質問を入力… (Enter で送信)',
  send: '送信',
  thinking: '考え中…',
  modelLabel: '使用中のモデル / Model',
  newLesson: '新しいレッスン',
  topicPrompt: '何を学びたい？（トピックを入力）',
  topicPlaceholder: '例: MP3の仕組み / How MP3 works …',
  nextChunk: '次へ',
  tidy: '⤢ 整列 / Tidy',
  replay: 'リプレイ',
  replayExit: '終了',
  replayPlay: '再生',
  replayPause: '一時停止',
  exportSession: 'エクスポート',
  importSession: 'インポート',
  importFailed: 'インポートに失敗しました',
  overwriteConfirm: '同じIDのセッションが既にあります。上書きしますか？',
  chunkLabel: 'レッスン',
  playgroundLabel: 'プレイグラウンド',
  playgroundMissing: '未登録のプレイグラウンドです',
  variableLabel: '変数',
  derivedLabel: '計算',
  goalLabel: 'ゴール',
  cycleError: '循環参照',
  computeError: '計算エラー',
  fireDemo: 'FIRE逆算デモ',
  examples: '📚 例 / Examples',
  questionLabel: '質問',
  answerLabel: '回答',
  // In-page dialog buttons
  dialogOk: 'OK',
  dialogCancel: 'キャンセル / Cancel',
  dialogSubmit: '送信 / Submit',
  dialogClose: '閉じる / Close',
  // Cloud login / sync
  cloudTitle: 'ログイン / Sign in to sync',
  cloudSynced: 'クラウド同期中 / Synced to cloud',
  signIn: 'ログイン',
  signUp: '新規登録',
  signOut: 'ログアウト',
  emailPlaceholder: 'メール / Email',
  passwordPlaceholder: 'パスワード / Password',
} as const;
