// All user-facing UI strings live here (JP/EN mix) for later i18n.
export const strings = {
  appTitle: 'なんでだっけ？',
  nande: 'なんで？',
  defaultQuestion: 'why is this the case?',
  backToSource: '↩ 元のテキストへ',
  askPlaceholder: '質問を入力… (Enter で送信)',
  send: '送信',
  thinking: '考え中…',
  replay: 'リプレイ',
  replayExit: '終了',
  replayPlay: '再生',
  replayPause: '一時停止',
  exportSession: 'エクスポート',
  importSession: 'インポート',
  importFailed: 'インポートに失敗しました',
  overwriteConfirm: '同じIDのセッションが既にあります。上書きしますか？',
  chunkLabel: 'レッスン',
  playgroundLabel: 'プレイグラウンド',
  playgroundMissing: '未登録のプレイグラウンドです',
  variableLabel: '変数',
  derivedLabel: '計算',
  goalLabel: 'ゴール',
  cycleError: '循環参照',
  computeError: '計算エラー',
  fireDemo: 'FIRE逆算デモ',
  questionLabel: '質問',
  answerLabel: '回答',
} as const;
