// All user-facing UI strings live here (JP/EN mix) for later i18n.
export const strings = {
  appTitle: 'なんでだっけ？',
  nande: 'なんで？',
  respond: '答える',
  checkUnderstanding: '❓ 答えて理解を確認 / Check my understanding',
  gotIt: '分かった',
  understoodTitle: 'このノードを理解済みにする / Mark understood',
  understoodProgress: '理解',
  defaultQuestion: 'why is this the case?',
  answerPlaceholder: 'あなたの答えを入力… / Type your answer… (Enter で送信)',
  yourAnswerLabel: 'あなたの答え',
  backToSource: '↩ 元のテキストへ',
  askPlaceholder: '質問を入力… (Enter で送信)',
  send: '送信',
  thinking: '考え中…',
  modelLabel: '使用中のモデル / Model',
  newLesson: '新しいレッスン',
  topicPrompt: '何を学びたい？（トピックを入力）',
  nextChunk: '次へ',
  tidy: '⤢ 整列 / Tidy',
  replay: 'リプレイ',
  replayExit: '終了',
  replayPlay: '再生',
  replayPause: '一時停止',
  exportSession: 'エクスポート',
  importSession: 'インポート',
  importFailed: 'インポートに失敗しました',
  overwriteConfirm: '同じIDのセッションが既にあります。上書きしますか？',
  chunkLabel: 'レッスン',
  playgroundLabel: 'プレイグラウンド',
  playgroundMissing: '未登録のプレイグラウンドです',
  variableLabel: '変数',
  derivedLabel: '計算',
  goalLabel: 'ゴール',
  cycleError: '循環参照',
  computeError: '計算エラー',
  fireDemo: 'FIRE逆算デモ',
  examples: '📚 例 / Examples',
  questionLabel: '質問',
  answerLabel: '回答',
} as const;
